### ISSUE TITLE
copyright/license from dustin/gojson should be respected as well

### ISSUE THREAD

**Issue by mschoch** [couchbase/go_json#1]
I appreciate the candor of the commit message admitting you stole it, but why not just do it right.  Just leave it and it's test in separate files, keep the original copyright at the top and add the LICENSE file from @dustin's repo.

**Comment by tleyden** [comment]
> but why not just do it right

Wouldn't forking https://github.com/dustin/gojson be the "right" way to do it?  That way the LICENSE file should come across w/o any effort.

**Comment by marcogrecopriolo** [comment]
There is now a partial implementation of jsonpointer which has been adapted to take advantage of our own performance improvements in encoding/json.
I have pulled LICENSE from @dustin's repo and added our own as well, since I have added extensive changes, and will be adding more (including a FindWithState())

**Comment by marcogrecopriolo** [comment]
@ceejatec I guess you can close this now - I can't.
